
services:
  session-service:
    image: session-service:latest
    container_name: session-service-app
    ports:
      - "5001:80"
    depends_on:
      - screensharing-service
      - videoconferencing-service
        
        
  screensharing-service:
    image: screensharing-service:latest
    container_name: screensharing-service-app
    ports:
      - "5005:80"



  videoconferencing-service:
    image: videoconferencing-service:latest
    container_name: videoconferencing-service-app
    ports:
      - "5003:80"
    depends_on:
      - openVidu
        
  openVidu:
    image: openvidu/openvidu-server-kms:2.17.0
    container_name: openvidu-app
    ports:
      - "4443:4443"
    environment:
      - OPENVIDU_SECRET=MY_SECRET
